security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }