apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    service: web
status:
  loadBalancer: {}
